### ISSUE TITLE
For contact only

### ISSUE THREAD

**Issue by tayyabferozi** [OJII3/N3D#1]
I am also having the same issue that you had in this one:

https://github.com/vercel/next.js/issues/47485

And I can't resolve. I also don't have the "_Link to the code that reproduces this issue_"... as it throws 404. Can you help me?

**Comment by OJII3** [comment]
Well, that was a simple mistake, and I have already deleted the repository. 

In that issue, I just fixed from
```tsx
export async function generateStaticParams() {
  return [ "blog" ];
}
```

to

```tsx
export async function generateStaticParams() {
  return [
    {
      slug: "blog",
    },
  ];
}
````

If you give me more information about your problem, I think I can help you.
